site_name: Ez2Cloud Docs
nav:  
  - Essentials Documentation:
    - "End-user": Essentials/index.md
    - Ez2Ckoud Entities: Essentials/Concepts/index.md
  - IT Admin and Tech Docs:
    - "Admin Docs": ITAdmin/index.md
    - "Initial Setup": ITAdmin/satserver.md
theme:
    name: cerulean
    nav_style: dark

        
